server:
  port: 8080
  http2:
    enabled: true

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/sms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    tomcat:
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
      initial-size: 5
      max-active: 10
      max-wait: 60000
      min-idle: 5
      max-idle: 10
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
      validation-interval: 0
      remove-abandoned-timeout: 180
      remove-abandoned: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false